### ISSUE TITLE
Questions Version 4.0.1 

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#113]
Hello Gianluca,
How was your Easter? 
We actually had nice weather in the Netherlands.
So we had to make use of that and tested a lot of wine ;) 
But I saw you have been busy....
I have a few questions. 
When looking at the changelog there is an entry:
>   Fixed: some files not being moved to the trash after a successful encoding
>   (if enable on  preferences).

When did this occur? (just curious). 
I had this once but after a restart of Videomass it worked fine again. (I'm using Linux, maybe this was the case with Windblows?)
I think the program (and/or the programmer of course) is quite intelligent as Videomass only moves the successful files of the batch to the trash and leaves the original of the "failed" in the original folder.   

I also saw:
> [Presets Manager] added optional pre-input parameters. These params will be placed before the first '-i' argument of the ffmpeg.

Where should I put these pre-input parameters?

I was wondering if it would be interesting/possible to have error messages that could be more instructive?
So eg. I had an error "[matroska @ 0x564c35fe16c0] Subtitle codec 94213 is not supported"
Maybe this could say: "Please convert to mp4, convert the subtitle(s) to srt (-c:s srt) or leave out the subtitle(s)."

Well that's it for now.
Ciao and have a nice evening!
J.

**Comment by jeanslack** [comment]
Hello @johannesdedoper,

We spent a beautiful Easter Monday, from morning to evening, we had a very good lunch in a beautiful location and we had a nice walk around the hills :+1: then back home I dedicated myself to the program :-)

> Fixed: some files not being moved to the trash after a successful encoding
    (if enable on preferences).
When did this occur? (just curious)...
...

This issue affected only the latest features of the program in versions 4.0.0 and 4.0.1, specifically `Still Image Maker` and` From Video to Pictures`. I was about to release version 4.0.0 when I noticed some problems yet.

>  also saw: 
[Presets Manager] added optional pre-input parameters. These params will be placed before the first '-i' argument of the ffmpeg.
Where should I put these pre-input parameters?

For the moment I have removed this function, because it requires further work and changes that I will evaluate better on the next versions. I prefer to take small steps in development and release at a time.

> I was wondering if it would be interesting/possible to have error messages that could be more instructive?
So eg. I had an error "[matroska @ 0x564c35fe16c0] Subtitle codec 94213 is not supported"
Maybe this could say: "Please convert to mp4, convert the subtitle(s) to srt (-c:s srt) or leave out the subtitle(s)."

For detailed reading of the logs given by FFmpeg and Videomass, you should open the log window (CTRL+L) and click on one of the entries in the **log file list**. If that's not enough for you, try increasing the verbosity of the logs: Open the preferences, click on the FFmpeg log level tab and set the level to **info** or **verbose**.

Let me know.
Ciao, Good evening!
G.

**Comment by johannesdedoper** [comment]
Hi G.

Thanks for your reply.
Nice to hear you had a good time too and did not work all the time ;)
I have another ¨small" idea, what I would like to have is the possibility to save the layout/size of the GUI.
So whenever you open Videomass it will scale and take the size and place on the screen as saved, also remebering the width of the columns (eg. the columns of the presets being "name", "description", "format¨).

Again, it is just an idea, not a gamechanger but nice to have.
Cheers for now.
J.

BTW, maybe this already possible for me by changing some file included with Videomas?

**Comment by jeanslack** [comment]
Hi,

The layout / size of the GUI should already be stored when closing the application (at least as regards the size of the main window. Doesn't this happen when you resize the main window and then close the program?

For window positioning when opening, modern DEs have smart repositioning activated, so it seems useless to me. 
Rather, I have often thought about adding a function to save the current session with a name.

**Comment by johannesdedoper** [comment]
Hi,
You are correct, the size is stored. 
Saving current sessions would be great, this way you can skip through a few steps. It would be nice for me to start directly in the presets manager skipping the main menu and if you are someone who wants to encode later it's a nice feature. 

For me that's not the most important thing.
The thing is that everytime you edit, duplicate or delete a preset or change something in the preset menu the columns reset.
To keep the column size and layout during a session of Videomass would already be great.

Cheers, have a nice Sunday!
J.

**Comment by johannesdedoper** [comment]
Hello,

it's me again.
I have another (bad) idea ;)
It would be nice to have the possibility to add more files to the queue when already converting started.
So when you forget a file you do not have to interrupt the encoding or start a new instance of Videomass.

Cheers,
J.

**Comment by jeanslack** [comment]
Hello @johannesdedoper,

For now it is not possible to accomplish what you ask for. I'm sorry.

Have a good weekend!

**Comment by johannesdedoper** [comment]
Ok, of course no problem.
Just ideas ;)

cheers,
J.

**Comment by johannesdedoper** [comment]
Hello Gianluca,

how are you? 
Just wanted to let you know I'm still very happy with Videomass.
I'm using the 4.0.1 now with language selector, nice.
Just curious, do you have any plans for the future regarding new features or new software (utilities)?

Well, anyway, have a nice day!
Cheers, 
J

**Comment by jeanslack** [comment]
Hello,
I'm fine and you?

> Just curious, do you have any plans for the future regarding new features or new software (utilities)?

Yes, I have some ideas to develop, as soon as I can I proceed. I am currently doing other things.

Soon!
