### ISSUE TITLE
Performing updates for yt-dlp

### ISSUE THREAD

**Issue by Aetavicus** [jeanslack/Videomass#169]
I do not see an option to update yt-dlp in Videomass. Clicking on regular update does nothing.

Additionally, I am also unable to find the executable for yt-dlp on my PC. I installed it using the Videomass installer. The current path for yt-dlp in the settings is "C:\Program Files (x86)\Videomass\yt_dlp" but there is no such folder on my PC. Hidden items are set to visible.

**Comment by jeanslack** [comment]
Please provide the version of Videomass you are using.

**Comment by Aetavicus** [comment]
I was using 4.0.1 at the time of this issue. I manually updated Videomass to 4.0.2 and it seems the yt-dlp executable is now also updated.

Is there a a way to manually update the yt-dlp executable?

**Comment by jeanslack** [comment]
I'm sorry but there is no way to update yt-dlp nor youtube-dl in the Videomass package provided with the installer for MS-Windows and macOS. Currently downloader updates are possible by installing Videomass via pip or using Linux.

> Additionally, I am also unable to find the executable for yt-dlp on my PC. I installed it using the Videomass installer. The current path for yt-dlp in the settings is "C:\Program Files (x86)\Videomass\yt_dlp" but there is no such folder on my PC. Hidden items are set to visible.

Since yt-dlp and youtube-dl are written in Python code, they are used internally as Python modules by Videomass and not as simple executables placed somewhere on your filesystem. 
In your case the solution is to wait for the new version of the program with the downloaders updated to the latest version.
