### ISSUE TITLE
[Announcement] Planning to remove the UI for youtube-dl / yt-dlp from Videomass

### ISSUE THREAD

**Issue by jeanslack** [jeanslack/Videomass#187]
Videomass will no longer have any functionality for downloading web videos. This mainly concerns reasons of maintainability of the source code. But if your requests are against this decision, perhaps I could consider developing another separate GUI for yt-dlp.

**Comment by 9Skrip** [comment]
please don't do that, Videomass is my favourite tool for downloading YouTube videos

**Comment by jeanslack** [comment]
There are tons of tools for downloading videos from websites now and I think there will be better ones in the future. On the other hand, there are many interfaces for FFmpeg too, but with the features that a small tool like Videomass offers, there aren't any (I haven't seen any). So I would like to focus on making this app better.

**Comment by Woolwit** [comment]
While it's very convenient to be able to download YTs, especially with your GUI for choosing options, I can appreciate that maintaining it alongside ffmpeg must be challenging. Because it's so easy, and I'm familiar with Videomass, it's been my goto for youtube-dl lately, but I noticed a few days ago youtube-dl is broken (again) and that folks are more or less moving to yt-dlp. I have some cli commands saved that will mostly get me what I need but I will miss the ease of Videomass. Either way thank you for Videomass!

**Comment by jeanslack** [comment]
When I have some free time I'll make a simple GUI for yt-dlp, the code is ready, I just need to clean it up and optimize it. Regarding youtube-dl it will be officially replaced by yt-dlp, at least for Linux.

**Comment by jeanslack** [comment]
**Update**
A public repository for the new project called [Vidtuber](https://github.com/jeanslack/Vidtuber) has been created. This app only allows interfacing with  [yt-dlp](https://github.com/yt-dlp/yt-dlp) and has many of the main features that were implemented in Videomass up to version 4.0.5, but overall with better source code management, which also benefits Videomass itself.

It has already been almost completely translated into French, Spanish, Russian, Dutch, Portuguese, Italian and Chinese languages.

Please report bugs and various inconsistencies to https://github.com/jeanslack/Vidtuber/issues/new/choose. 
Pull requests are welcome.
Thank you.
