### ISSUE TITLE
Automatic encoder selection failed for output stream #0:1. Default encoder for format avi (codec none) is probably disabled

### ISSUE THREAD

**Issue by jhcuarta** [jeanslack/Videomass#217]
Hi
I encounter this error while I was trying to convert a .mp4 file to .avi

**Automatic encoder selection failed for output stream #0:1. Default encoder for format avi (codec none) is probably disabled. Please choose an encoder manually.**

I tried all encoders avaiable but no success, I was wondering if there is a way to download more encoders or the application just can´t convert the file
 I'm using ubutnu 22.04
Videomass v4.0.10

**Comment by jeanslack** [comment]
Hi @jhcuarta,

I don't think I can give you a solution to your problem with so little information. What feature are you using on Videomass for your purpose? are you using **A/V Conversions** or **Presets Manager**?

General questions usually give generic answers:

First of all you should check how many streams are in your video and if they are indexed correctly. Check this using the Properties tool in the toolbar.

If you only need to convert from one format to another and you know that the codecs used for one format are also compatible for the other, you can skip the re-encoding and do a simple remuxing. 

### So, what codecs are implemented in the video you imported to Videomass and how are the streams indexed?

Also, can you send me a small portion of your video so I can find out the error and give you the solution?

**Comment by jhcuarta** [comment]
Hi
I was trying A/V Conversions, I dont know how to do a simple remuxing. I don't know how to take a small portion of the video so I send you a link of the movie. It had happened with other films, I don't know how to procced

https://drive.google.com/file/d/1HJ6NEC7VZ0YmTbht6l7IVsiKPYohLfHl/view?usp=sharing

Best regards

**Comment by jeanslack** [comment]
Sorry but I can't download the video from your URL, it says there was an error connecting to google drive.

**Comment by jhcuarta** [comment]
Hi
I'm just trying to change format to .avi, my appologies for my lack of expertise. I'll send you a new link

https://drive.google.com/file/d/1RJH4uJGkUP0qU5qIoajAA4B4xpF0LlsY/view?usp=sharing

Best regards

**Comment by jeanslack** [comment]
I'm sorry for the failure but I can't download your video, by the way it's too big for me.
However if you managed to change the format to .avi it is already a good result.

> I was trying A/V Conversions, I dont know how to do a simple remuxing

Remuxing means changing the video container only. It is a lossless process that the original audio and video data is kept untouched. The opposite to remuxing is transcoding, which means the conversion of one encoding method to another. The source data is changed during the transcoding, hence a lossy process.

In general your problem may concern a stream not supported by the format you want to convert. But since I can't give you a sure answer, I'm afraid I can't help you with this.

Try taking a look at the following web pages:
https://superuser.com/questions/1482543/ffmpeg-seems-to-be-unable-to-transmux-when-remapping-streams
https://superuser.com/questions/1527634/what-options-to-use-to-convert-video-with-a-given-video-audio-subtitle-stream
