### ISSUE TITLE
Input file name containing single quote (') are not accepted

### ISSUE THREAD

**Issue by chrisadas** [jeanslack/Videomass#224]
**What operating system are you using?**   
Windows 10 22H2

**What version of Videomass are you using and how did you install or run it?**   
v5.0.0_x86_64 portable

**Describe the bug**   
When adding input files by dragging them into the GUI window, any files containing single quote (') are not added. This happened both with the single quote being in the file name or directory name.

**Comment by jeanslack** [comment]
Hello @chrisadas 

It's not exactly a bug, although it looks like it. This is an expected behavior of this application, and was requested because some operations like file concatenation are really problematic with pathnames having single or double quotes.

Also, a warning message should appear in the status bar when importing quoted pathnames. Do you confirm this?

**Comment by chrisadas** [comment]
Hi @jeanslack  I see. Yes, the status bar does show "file has illegal characters like: ", which I did not noticed before.

I don't know if it has much value for others, but additional information here like number of files that are rejected or list of them would be cool.

**Comment by jeanslack** [comment]
You are right, your proposal is good and I think I will implement it soon, 
thanks!
