### ISSUE TITLE
App doesn't start when locale is set to esperanto (macOS 10.14.6)

### ISSUE THREAD

**Issue by gsurrel** [jeanslack/Videomass#26]
When the system locale is set to Esperanto, the app refuses to start with the following hard warning:

<img width="532" alt="bildo" src="https://user-images.githubusercontent.com/1993113/123082134-fcc7ec00-d41e-11eb-9d3e-dd3ff931bb8f.png">

This has been tested on macOS 10.14.6.

Additional notes: it starts when setting it to "French (France)", and still doesn't start when going back to Esperanto afterwards.

**Comment by jeanslack** [comment]
hi @gsurrel
Thanks for reporting. I will do a research for this problem.

**Comment by jeanslack** [comment]
hi @gsurrel

I found these interesting links for your problem:
[https://discuss.wxpython.org/t/locale-problems-in-wx-python/34724](https://discuss.wxpython.org/t/locale-problems-in-wx-python/34724)
[https://discuss.wxpython.org/t/what-is-wxpython-doing-to-the-locale-to-makes-pandas-crash/34606](https://discuss.wxpython.org/t/what-is-wxpython-doing-to-the-locale-to-makes-pandas-crash/34606)

It does not seem like a problem on the Videomass code but incompatibility of the wxPython toolkit due to some changes made recently on Python.
The only thing that can be done now is to wait for the fixes.
