### ISSUE TITLE
Suggestions/Remarks concerning the interface and AV1 encoding

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#260]
Hello, there !

Still loving this program, especially it's flexibility.

Few things that I noticed using AV1 encoding.
The q: rating is different as expected, encoding with Nvenc qv of 35 it shows a q of 80-90
It's not really important, just not consistent or in line with the setting (see picture)
![Selection_049](https://github.com/jeanslack/Videomass/assets/100475891/4ca8256b-7ea7-43ba-9db2-58e7c62276c9)

An few minor annoyances for me are when restarting/starting Videomass 
1. not being able to turn off any check on updated presets and the popup as seen below.
![Selection_050](https://github.com/jeanslack/Videomass/assets/100475891/8ec888f0-5878-4b46-baf5-420080b756f0)
When clicking "yes" gives me an error:
![Selection_051](https://github.com/jeanslack/Videomass/assets/100475891/c2ebcf8f-4558-49ba-95dd-c6cdc1485580)

2. another thing (that's more important to me) is the start up size of the program including all columns/windows 
See picture below, every-time I restart/start it makes the columns some default size, not the last used or saved size.  
Therefore not showing the whole name of a preset, as I would like.
![Selection_052](https://github.com/jeanslack/Videomass/assets/100475891/60d11b9c-add0-4a9f-abb8-c80c39e4247d)

Anyway keep up the fine work.
Ciao,
J.

**Comment by jeanslack** [comment]
Hello!

> Still loving this program, especially it's flexibility.

Thank you very much! My intent was to make it flexible, but there is still a lot to work on...

> Few things that I noticed using AV1 encoding.
The q: rating is different as expected, encoding with Nvenc qv of 35 it shows a q of 80-90
It's not really important, just not consistent or in line with the setting (see picture)

The `q:` rating is calculated by ffmpeg, not Videomass.
I don't even want to try to fix this kind of data if users find it wrong. In this case it might be more useful to report the problem to the ffmpeg developers. I'm afraid I can't solve this issue.

> An few minor annoyances for me are when restarting/starting Videomass 
not being able to turn off any check on updated presets and the popup as seen below. When clicking "yes" gives me an error

This bug should have been fixed in the latest program version v5.0.4 (see #258)
You are obviously using an older version of the program. Please update it to version [5.0.4](https://github.com/jeanslack/Videomass/releases/tag/v5.0.4) .

> another thing (that's more important to me) is the start up size of the program including all columns/windows
See picture below, every-time I restart/start it makes the columns some default size, not the last used or saved size.
Therefore not showing the whole name of a preset, as I would like.

You're right, by the way we already talked about it some time ago (see https://github.com/jeanslack/Videomass/issues/113#issuecomment-1106642599). This implementation will take me some time and for now I don't have any. However it is still on the TODO list and I will do it when I can.

I hope I have clarified everything, if not, do not hesitate to request information.

Let me know!

**Comment by johannesdedoper** [comment]
Thanks!

You are right, I use the 5.0.2., time to upgrade :)
Understand your answers and appreciate any efforts improving this great tool.

Cheers,
J.

**Comment by jeanslack** [comment]
Ok, this issue will be closed as soon as I merge the active branch with the master. I've tested a few things but it's never enough. Please let me know if you experience any malfunctions.
