### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by trabant-asb** [jeanslack/Videomass#267]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
Devuan Chimaera (arm64)

**What version of Videomass are you using and how did you install or run it?**   
Videomass 5.0.4 from python3-videomass_5.0.4-1_all.deb

**Describe the bug**   
When selecting "Youtube Downloader", an error message pops up complaining about a missing /usr/lib/python3/dist-packages/videomass/art/icons/Videomass-Colours/16x16/subtitles.png . As a workaround, I converted the existing subtitles.svg accordingly and put it into place.

**Comment by jeanslack** [comment]
Hi Alex,
Thanks for reporting this issue.

I didn't notice this, it was probably a recent accidental deletion.

Unfortunately I won't be able to solve this Videomass problem on wxPython v4.0.7, i.e. the one you are using on Devuan Chimaera, because now the development is oriented towards supporting only wxPython v4.1.1 or higher (i.e. the one available on Devuan Daedalus and Debian 12) .

In short, the explanation is that wxPython v4.0.7 does not support SVG images but only PNG images, while the new versions support both formats, but I made a choice, that of using only icons in SVG format for their high definition, deleting all icons in PNG format from Videomass sources.

As a workaround, and fix this problem on Devuan Chimaera, you can install a fully compatible newer version of wxPython: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-11/

**Comment by trabant-asb** [comment]
Hi,
No problem with that. The purpose of the issue I filed was primarily informational... 
...as I was able to recreate the missing file, I don't expect you to bring up a solution.

Keep the good work up,
-Alex
