### ISSUE TITLE
Is there a way to change the font size of the presets?

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#271]
Hello,

Great work 5.0.6 including the fixed columns width.
So fast, Thanks. Mille grazie!

A have a small question, can I change the font size somewhere?
Maybe you can point me to a file which I can moderate?
I don't know why, but the font size is smaller than in 5.0.2 on my PopOs linux.

Anyway, have a very nice weekend!
Cheers
J.

**Comment by jeanslack** [comment]
The font size has not been changed on Videomass and is not intended to be changed by the user.

**Questions:**
- How did you install Videomass? from PPA, PyPi, using source code, installing .deb file?
Or is Videomass included in the PopOs linux software repository?

- What version of Python and wxPython is Videomass using? (To know this for sure, click on the menu bar Help -> System Version).

- Have any system updates been made other than Videomass?

It's difficult to answer, because your problem could depend on various things.

**Comment by johannesdedoper** [comment]
Ok, no problem, I just tweaked the OS fonts a bit and every is fine now.
Was just curious.
FYI, The 5.0.2. I used was an Appimage, for the 5.0.6 I used the PPA.

Thanx again for the quick reply.
Cheers, J.
