### ISSUE TITLE
 Debug: window 

### ISSUE THREAD

**Issue by wmport** [jeanslack/Videomass#284]
## Thanks for taking the time to ask a question!
in ubuntu logs

20:47:58 videomass: 08:47:58 PM: Debug: window wxMenuBar@0x20d5fff0 ("menubar") lost focus even though it didn't have it

**Comment by jeanslack** [comment]
Thanks for reporting, but I can't give you answers if you don't at least provide the version of the software you're using:
Which version of Ubuntu are you using?
Which version of Python and which version of wxPython?

**Comment by wmport** [comment]
Linux ubuntu-desktop 6.1.0-1004-rockchip #4-Ubuntu SMP Sat Mar 23 02:54:13 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

Python 3.12.2

**Comment by jeanslack** [comment]
Can you also provide the version of wxPython installed on your system? `python3 -c "import wx; print(wx.version())"`

**Comment by wmport** [comment]
python3 -c "import wx; print(wx.version())"
4.2.1 gtk3 (phoenix) wxWidgets 3.2.4

**Comment by jeanslack** [comment]
Thanks for the info.
So this problem is not directly related to malfunctions in the Videomass code but seems to be related to the wxWidgets/wxPython toolkits under Wayland. Since the wxWidgets and wxPython developers are probably working to resolve this problem, we await the fix.

In the meantime, as a workaround try switching to X11 to suppress those annoying messages.

**Comment by wmport** [comment]
ok!
