### ISSUE TITLE
Lots of (false?) positives on VT for your exe

### ISSUE THREAD

**Issue by tyeeman** [jeanslack/Videomass#31]
Your portable exe. Maybe you know that, maybe not? I'm afraid to run your app!

**Comment by jeanslack** [comment]
hi @tyeeman  
thanks to report

I just scanned the executables with VirusTotal and still saw 9 vendor detections. 
Also, I checked with windows defender and it detected Trojan:Win32/Zepvedo.B (Videomass.exe).
I thought the virus problem was solved https://github.com/jeanslack/Videomass/issues/16# .

The standalone Videomass executables for MS-Windows (and also for MacOS) are created with [pyinstaller](https://github.com/pyinstaller/pyinstaller) and It's well know that some antivirus software raise false positive with exe created from [pyinstaller](https://github.com/pyinstaller/pyinstaller).

**Comment by jeanslack** [comment]
I have successfully tried this workaround: https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html 
... (more than 2GB of Visual Studio c++ Compiler) but VirusTotal detected 14 positives yet.
this is annoying to me, i will probably stop distributing exe for windows. 

just for information: https://github.com/pyinstaller/pyinstaller/issues/6062

**Comment by tyeeman** [comment]
OK then, can I just download the zipped code of your repo then go into the Videomass folder and run the .py file there?

**Comment by jeanslack** [comment]
From a VT analysis on the zipped sources: https://www.virustotal.com/gui/file/b423c1475d207239093cf281e0b630a87871e0c7cf3da12259fbb6ef78ecc567/detection

I had to delete the AESTD1004_1_15_10.pdf file from the docs folder. The sources seems OK : https://www.virustotal.com/gui/url/cd1ea4e0ee2246113874c4e2b15f0939f9107a0fd9aa211833b7f2d9fcab4e5c/detection
AESTD1004_1_15_10.pdf I found it here: https://www.aes.org/technical/documents/AESTD1004_1_15_10.pdf

UPDATE - today I tried to build the MS-Windows bundle with Pyinstaller and Windows Defender did not detect any virus on the exe. But not on VirusTotal.

**Comment by tyeeman** [comment]
I used pyinstaller a few months ago and used the one file option, have you tried that?

**Comment by jeanslack** [comment]
Current sources (by latest release v.3.4.5) : https://www.virustotal.com/gui/file/e8f093e690c476ea79f35c428d54b60b7180eee8cdbd8ea09cf0a334187e9878/detection

---
with --onedir option: https://www.virustotal.com/gui/file/3219e5ee878c4ba6fee97284936f6cb1f3b50a87b6d77740679c6ad1c6fbf699/detection

---
with --onefile option: https://www.virustotal.com/gui/file/4ac1f571d299cac5040a337ee4ad803275a8b94cd2aebc4cd1d3dad5a29fb9b3/detection

**My cents:** with the onefile option VirusTotal detects 5 security vendors who mark the file as malicious (instead of 15 with onedir enabled). Consider that I compiled the bootloaders myself and used those for the bundles, making the application better accepted by the heuristics based AVs. 
Since these are false positives, the only thing to do is to submit the Videomass.exe file to your antivirus vendor for advanced analysis and making a False Positive claim. (at least for Videomass version 3.4.5). 
I'll give it another chance then.
