### ISSUE TITLE
Console window during download [Windows]

### ISSUE THREAD

**Issue by smaragdus** [jeanslack/Videomass#38]
Hello,

While downloading videos with version [3.5.0](https://github.com/jeanslack/Videomass/releases/tag/v.3.5.0) a console window flashes several times during the download (it was just for a second so I could not take a screen-shot). While using version [3.4.6](https://github.com/jeanslack/Videomass/releases/tag/v.3.4.6) no console window appears while downloading at all. Can you confirm this? This is is not a big issue but I don't think this is supposed to happen, right?

On a side note I think that [Videomass](https://jeanslack.github.io/Videomass/) version [3.5.0](https://github.com/jeanslack/Videomass/releases/tag/v.3.5.0) cannot use the settings created by version [3.4.6](https://github.com/jeanslack/Videomass/releases/tag/v.3.4.6), right?

Regards

**Comment by jeanslack** [comment]
Hello,

I too have noticed this annoying problem which affect MS-Windows, but I couldn't do anything about it with the Videomass code, the explanation is as follows: 

In all previous versions of Videomass, youtube-dl was run as a subprocess, with which I could easily prevent displaying console window. In Videomass version 3.5.0, since youtube-dl and yt-dlp are embedded only as Python modules (for the purpose of improving the code implementation and its effectiveness), preventing the console window from being displayed is impossible: The reason is that the youtube-dl and yt-dlp Python code, although embedded in other Python code, is not meant to be implemented on a GUI at all.

**The good news:** Today hacking the youtube-dl code I found a workaround, so I would know how to solve this problem, but I should open a [PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) in the [youtube-dl](https://github.com/ytdl-org/youtube-dl/) and [yt-dlp](https://github.com/yt-dlp/yt-dlp) repos, and will probably do so soon.

> On a side note I think that Videomass version 3.5.0 cannot use the settings created by version 3.4.6, right?

With Videomass version 3.5.0 comes a new configuration file, which will start the wizard dialog. The same will happen if you start a previous version of Videomass with a different version of the configuration file.

**Comment by smaragdus** [comment]
@jeanslack 

Thank you for the informative response.

From user's perspective- isn't using the executables- **youtube-dl.exe** and **yt-dlp.exe** a better solution? I mean- there have been many [youtube-dl](https://github.com/ytdl-org/youtube-dl) front ends and even when they are abandoned the users can manually update the executable file and thus they can continue to use the abandoned front end. What do you think?

By the way it seems that [youtube-dl](https://github.com/ytdl-org/youtube-dl) might be abandoned. So I compared the download results using [youtube-dl](https://github.com/ytdl-org/youtube-dl) and [yt-dlp](https://github.com/yt-dlp/yt-dlp) with [Videomass](https://github.com/jeanslack/Videomass) and there is a difference:

- Using [youtube-dl](https://github.com/ytdl-org/youtube-dl) with default options the downloaded video is in MP4 format:
- Using [yt-dlp](https://github.com/yt-dlp/yt-dlp) with default options the downloaded video is in WEBM format:

Is there a simple way to force [yt-dlp](https://github.com/yt-dlp/yt-dlp) to use MP4 in stead of WEBM without using **Download by format code** option?

Regards

**Comment by jeanslack** [comment]
> From user's perspective- isn't using the executables- youtube-dl.exe and yt-dlp.exe a better solution? I mean- there have been many youtube-dl front ends and even when they are abandoned the users can manually update the executable file and thus they can continue to use the abandoned front end. What do you think?

My point of view: From user's perspective, one of the direct advantages is undoubtedly the increase in security, then there are also indirect advantages such as making the code more easily maintainable, which is a non-negligible investment in the event that the project is abandoned. 

> By the way it seems that youtube-dl might be abandoned. So I compared the download results using youtube-dl and yt-dlp with Videomass and there is a difference:

Since I'm in favor of free and open-source formats, I didn't care too much about this (WEBM is a BSD-style licensed  open-source format). Evidently the yt-dlp users had made this request and were satisfied. We may ask the developers of Yt-dlp for more information.

> Is there a simple way to force yt-dlp to use MP4 in stead of WEBM without using Download by format code option?

Currently on Videomass there is no way to choose a video format unless you download using the format codes. But in the future I might add an option to choose the video format as well.

**Comment by smaragdus** [comment]
@jeanslack 

> Currently on Videomass there is no way to choose a video format unless you download using the format codes. But in the future I might add an option to choose the video format as well.

An option for choosing the video format for download would be great for me as there would be no need to convert the downloaded file.

**Comment by jeanslack** [comment]
Ok, I'll leave this issue open until the console window flashing problem is solved.

**Comment by jeanslack** [comment]
I reported this issue to [yt-dlp](https://github.com/yt-dlp/yt-dlp), please refer to https://github.com/yt-dlp/yt-dlp/issues/1251

**Comment by smaragdus** [comment]
@jeanslack 

Thanks for taking your time to report this.

**Comment by jeanslack** [comment]
Since this issue has been [fixed](https://github.com/yt-dlp/yt-dlp/issues/1251) and [merged](https://github.com/yt-dlp/yt-dlp/pull/1261) into yt-dlp master, I close it.

**Comment by smaragdus** [comment]
@jeanslack 

Thanks!

**Comment by jeanslack** [comment]
@smaragdus 
I just released Videomass 3.5.1

**Comment by smaragdus** [comment]
@jeanslack 

I have just tested version [3.5.1](https://github.com/jeanslack/Videomass/releases/tag/v.3.5.1) and the console window appeared only once, at the beginning of the download. Did you experience the same?

Anyway, your support is impeccable! Thanks for the video format selection option too! Excellent work!

Regards

**Comment by smaragdus** [comment]
By the way I am curious- why did you delete the project from [SourceForge](https://sourceforge.net/projects/videomass2/)?

**Comment by jeanslack** [comment]
> I have just tested version 3.5.1 and the console window appeared only once, at the beginning of the download. Did you experience the same?

No, it didn't appear to me in the last few tests.

> By the way I am curious- why did you delete the project from SourceForge?

The main reason is that I do NOT have fast upload bandwidth. Since Github can host all my assets, it seemed pointless to keep the project on SourceForge as well. It was a tough decision but I had to make choices to avoid wasting more time and resources.

**Comment by smaragdus** [comment]
> The main reason is that I do NOT have fast upload bandwidth. Since Github can host all my assets, it seemed pointless to keep the project on SourceForge as well. It was a tough decision but I had to make choices to avoid wasting more time and resources.

I see. Let's hope that GitHub won't follow the route of Google Code and CodePlex.
