### ISSUE TITLE
ITV hub d/l

### ISSUE THREAD

**Issue by footballdvd** [jeanslack/Videomass#49]
I am logged into a paid Hub account, using a dedicated line VPN that works to stream this link through the website but d/l produces the following error.
[ITV] 1a6464a0058: Downloading webpage
ERROR: 'dict_items' object is not reversible
[Videomass]: FAILED !
[Videomass]: completed, but not everything was successful.

Nothing is in the folder. Any solutions for this problem? Thanks.

Here is the link:
https://www.itv.com/hub/the-big-match-revisited/1a6464a0058

**Comment by jeanslack** [comment]
Hello @footballdvd 

Which downloader did you use for that operation with Videomass? **youtube-dl** or **yt-dlp**?
However the problem you reported is not (strictly) related to Videomass, but it is in the downloader engine you used. 
Searching on [yt-dlp issues](https://github.com/yt-dlp/yt-dlp/issues?q=ITV+hub) I noticed that this problem has already been closed and will probably be fixed in the next yt-dlp release.
See:
https://github.com/yt-dlp/yt-dlp/issues/1775 (opened 5 days ago)
https://github.com/yt-dlp/yt-dlp/issues/1758 (opened 6 days a go)

**Comment by footballdvd** [comment]
Hi @jeanslack Thanks for the quick response. I am using 'yt-dlp' version 2021.11.10.1. I see your update so will hope this update works. Thanks.

**Comment by jeanslack** [comment]
OK, as soon as I release the new version of Videomass I will also include the new version of [yt-dlp](https://github.com/yt-dlp/yt-dlp). By the way, can you also tell me which operating system you are using and how did you install Videomass? Thanks.

**Comment by footballdvd** [comment]
I use Mac OSX Mojave and I downloaded from VideoHelper DMG site (version 3.5.2).

**Comment by jeanslack** [comment]
OK, thanks for the info. I just released a new version of [Videomass (3.5.3)](https://github.com/jeanslack/Videomass/releases/download/v.3.5.3/Videomass-v3.5.3-x86_64.dmg). It includes the latest yt-dlp update which should fix your problem. Let me know.

**Comment by footballdvd** [comment]
Excellent. Thanks for updating the thread. This works beautifully. Very fast and complete. Thank you.

**Comment by jeanslack** [comment]
Thanks for using Videomass.
