### ISSUE TITLE
Downloading m3u8 information => ERROR: unknown locale: fr-BE

### ISSUE THREAD

**Issue by Lodhar** [jeanslack/Videomass#60]
Hi,
I am using Videomass for a while now. Good job really! I was using the v3.3.8, no problem there. Since the version3.5.0, I cannot download certain videos. I tried the new version tonight and got the same exception. I get this when it start:

```
URL 1/1
Source: https://www.rtbf.be/auvio/detail_nos-femmes?id=2858885
[RTBF] 2858885: Downloading webpage
[RTBF] 2858885: Downloading m3u8 information
ERROR: unknown locale: fr-BE
[Videomass]: FAILED !
```

I use the portable version on Windows 10 (21H1). 
What kind of informations do you need to look into that?

**Comment by jeanslack** [comment]
Hi,
Which downloader were you using when you got that error?

**Comment by Lodhar** [comment]
I tried both youtube_dl and yt_dlp. Restart needed for the change.

**Comment by jeanslack** [comment]
I tried to copy your URL but I was unable to reproduce your error on my PC. With Videomass default settings it starts downloading but then I get: 

`ERROR: unable to download video data: HTTP Error 403: Forbidden`

Using yt-dlp from command line i get the same error. 
```yt-dlp https://www.rtbf.be/auvio/detail_nos-femmes?id=2858885
[RTBF] 2858885: Downloading webpage
[RTBF] 2858885: Downloading m3u8 information
[info] 2858885: Downloading 1 format(s): hls-4256
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 697
[download] Destination: Nos femmes [2858885].mp4
[download]   0.1% of ~2.13GiB at 479.21KiB/s ETA 01:17:30 (frag 1/697)ERROR: unable to download video data: HTTP Error 403: Forbidden

```
The site probably requires registration. 

In any case, this is not a Videomass problem, but of the downloaders (or the site) as even if something has changed in Videomass 3.5.5 compared to version 3.3.8 the command parameters are the same.

**Comment by Lodhar** [comment]
Yes, the site requires registration. But if I use Open Video Downloader or TVDownloader, it's working. OVD use yt-dlp (v2022.02.04) and TVD use youtube_dl (v2021.06.06). This is why I thought it to be a Videomass problem.

After reading your answer, I used Process Explorer to see what was the processe failing and I see a ffprobe in the process tree getting red and dying.  But I compare the ffprobe verion on the 4 programs (OVD, TVD, VM3.3.8 and 3.5.5) and it does not seems to be the problem. 

Searching again, I found some logs in your application, showing this:
```
[DATE]:
19-02-22 01:48:59

[LOCATION]:
C:\Users\user\AppData\Roaming\videomass\log\youtubedl_lib.log

[VIDEOMASS]:
{'compat_opts': 'all', 'format': 'hls-4256', 'extractaudio': '', 'outtmpl': 'C:\\Users\\user/%(title).100s.f%(format_id)s.%(ext)s', 'writesubtitles': False, 'addmetadata': False, 'restrictfilenames': False, 'ignoreerrors': True, 'no_warnings': False, 'writethumbnail': False, 'noplaylist': True, 'playlist_items': None, 'nooverwrites': False, 'no_color': True, 'nocheckcertificate': True, 'ffmpeg_location': 'D:\\Program Files (x86)\\Videomass\\FFMPEG\\bin\\ffmpeg.exe', 'postprocessors': [], 'logger': <videomass.vdms_threads.ydl_downloader.MyLogger object at 0x000001AC4BE34D90>, 'progress_hooks': [<function my_hook at 0x000001AC4B24A670>]}

[YOUTUBE_DL]: DEBUG > [RTBF] 2858885: Downloading webpage
[YOUTUBE_DL]: DEBUG > [RTBF] 2858885: Downloading m3u8 information
[YOUTUBE_DL]: ERROR: unknown locale: fr-BE
```
And I don't understand why it is calling youtube_dl when yt-dlp is configured. I saw the path set to "D:\Program Files (x86)\Videomass\yt_dlp" but I don't see anything that look like yt-dlp or youtube_dl. Just fishing here.

So I tried to change the path to another version of the downloader, but I can't. It seems that you included the downloaders coded in python. So I looked further, and search for "unknown locale" on Google, found a few exceptions in python (way over my head here).  Would it be possible to use an external version of the downloaders and not the ones coded in python? 

ps: sorry for those last lines. Too late for me and really tired.

**Comment by jeanslack** [comment]
Don't be sorry, indeed thanks for wanting to deepen a bit. 

1) That log was created by Videomass and is always identified as `youtubedl_lib.log` and  `[YOUTUBE_DL]` whether the `youtube_dl` module or the `yt_dlp` module is used (in the next versions I could improve this aspect). 

2) Since they are both written in Python, Videomass uses these downloaders as Python modules and not as subprocesses that run external programs. Their codes are loaded when Videomass is started and both are never loaded but only one or the other. You can check exactly which module is loaded by going to the Settings -> Preferences menu, then go to the Downloader tab and check the path on 'Current path' text field. 

That said, modules are very unlikely to load incorrectly, as the log messages have minor differences when using one downloader or the other. 

I would be very grateful if you could take the following test:
- Download https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
- Open a console window in user mode (not admin)
- In the command prompt drag in the file you just downloaded (yt-dlp.exe) 
- Press space bar to place a space then add `-f hls-4256 https://www.rtbf.be/auvio/detail_nos-femmes?id=2858885`
- Now hit enter, to execute yt-dlp.

This command replicates exactly the options you set on Videomass. Check what happens, copy the output and paste it here.
Thank you

**Comment by Lodhar** [comment]
There it is :
```
PS C:\Users\user\Downloads> .\yt-dlp.exe -f hls-4256 https://www.rtbf.be/auvio/detail_nos-femmes?id=2858885
[RTBF] 2858885: Downloading webpage
[RTBF] 2858885: Downloading m3u8 information
[info] 2858885: Downloading 1 format(s): hls-4256
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 697
[download] Destination: Nos femmes [2858885].mp4
[download]  11.6% of ~2.56GiB at  6.15MiB/s ETA 05:11 (frag 80/697)
```

```
[download] 100% of 2.70GiB in 07:07
WARNING: 2858885: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically
```

**Comment by jeanslack** [comment]
OK now we know that the problem concerns Videomass (even if indirectly) and appears to affect Windows only (from my tests). 
On Windows I am using Python 3.9.7 and wxPython 4.1.1 to build the executable packages as well. 

The problem is that since Python 3.8 there have been some changes to the locale and this broke some wxPython compatibilities; Here are just a few discussions: 
https://discuss.wxpython.org/t/a-few-more-windows-locale-related-remarks/34788
https://discuss.wxpython.org/t/wxpython4-1-1-python3-8-locale-wxassertionerror/35168
https://discuss.wxpython.org/t/what-is-wxpython-doing-to-the-locale-to-makes-pandas-crash/34606

For me the solution was downgrading to Python 3.7.9 and wxPython 4.0.7. 
Videomass seems to work correctly no longer showing that error message related to the unknown locale. 
I have already included a new portable package on the assets which may solve this issue: https://github.com/jeanslack/Videomass/releases/download/v.3.5.5/Videomass-v3.5.5_x86_64-portable-fix-locale.7z

**Comment by Lodhar** [comment]
Well done! It worked:
```
URL 1/1
Source: https://www.rtbf.be/auvio/detail_nos-femmes?id=2858885
[RTBF] 2858885: Downloading webpage
[RTBF] 2858885: Downloading m3u8 information
[info] 2858885: Downloading 1 format(s): hls-4256
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: My_Files\Nos_femmes-2858885.fhls-4256.jpg
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 697
[download] Destination: My_Files\Nos_femmes-2858885.fhls-4256.mp4
[Videomass]: SUCCESS !
Done downloading, now converting ...
[FixupM3u8] Fixing MPEG-TS in MP4 container of "My_Files\Nos_femmes-2858885.fhls-4256.mp4"
[Metadata] Adding metadata to "My_Files\Nos_femmes-2858885.fhls-4256.mp4"
[EmbedThumbnail] mutagen: Adding thumbnail to "My_Files\Nos_femmes-2858885.fhls-4256.mp4"
WARNING: unable to embed using mutagen; None
[EmbedThumbnail] Neither mutagen nor AtomicParsley was found. Falling back to ffmpeg
[EmbedThumbnail] ffmpeg: Adding thumbnail to "My_Files\Nos_femmes-2858885.fhls-4256.mp4"
Deleting original file My_Files\Nos_femmes-2858885.fhls-4256.jpg (pass -k to keep)

Successfully completed !
```
Thank you a lot for the time you put into this. Nice job!

**Comment by jeanslack** [comment]
Thanks a lot to you for your appreciation.
Soon I will release a new version that will also solve another problem mentioned in this issue. Also I hope that the Python locale issues will be fixed so that we can also use more up-to-date software in the future.
