### ISSUE TITLE
Estimated Remaining Encoding time

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#81]
Hello, I'm back ;) 
I got a new request.
I would like to see the remaining encoding time when encoding a file.
Would that be a feature to implement?

Cheers,
J.

**Comment by jeanslack** [comment]
Hello @johannesdedoper, welcome back.

The **Estimated Remaining Encoding time** has been removed from Videomass v3.4.1, because it is subject to errors and inaccuracies (especially when using the "Pictures_from_video" preset).
But if you give me good reasons to re-implement it I might consider your request. 

Cheers,
G.

**Comment by johannesdedoper** [comment]
It's a nice to have feature as you can estimate how long the encoding of eg. 10 of the same files will take.
So I can go and have a coffee (kidding) ;)
Cheers,
J.

**Comment by jeanslack** [comment]
I realize. I'll see what I can do but I want a coffee too ;)

**Comment by johannesdedoper** [comment]
LOL, it's not really crucial so just when you want to and if it is not giving you any other issues.

**Comment by johannesdedoper** [comment]
Wow, this converter keeps getting better! 
Do not understand why I didn't find this tool earlier. 
Did you add this to the videohelp.com website recently perhaps?
Anyway, thnx for the upgrade.

**Comment by jeanslack** [comment]
Thank you for appreciation. I didn't add it to videohelp.com. I just contacted the administrator to update the program description.
