### ISSUE TITLE
FFplay error - filename spaces

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#99]
Hello again,

I'm back ;)
Thanks again for the nice updates in 3.5.8!
I hope you do not mind but I found an issue when trying to play files in the input queue.
A file will not play having spaces in the filename.
See screenshot. 

Removing or replacing the spaces with eg. _ will resolve the issue.

Cheers again,
J
![Selection_016](https://user-images.githubusercontent.com/100475891/160259850-0318740f-bc6a-4f52-87ea-f5ed37a36350.png)
.

**Comment by jeanslack** [comment]
Hello,

> I hope you do not mind...

Absolutely not, indeed I thank you for your reports.
But, are you sure your file actually exists in that path? Because I had no problem playing a file with spaces in the filename as you can see from my screenshot:

![ffplay](https://user-images.githubusercontent.com/8676484/160269412-b3569b52-6b5b-40c3-9b4f-a6396dd8cb83.png)

**Comment by johannesdedoper** [comment]
You are right, it's working. I think the issue was a refresh. I use Double Commander and have automatic refresh turned off. So when some file is changed it will not show the change automatically. So when eg. renamed it will not show. I think this was the case. Sorry, my bad.

BTW:
1. type error on the page https://jeanslack.github.io/Videomass/Contribute.html . It says TRASLATING iso TRANSLATING
2. Can you please explain: "setting timestamp" within settings. Can not find any documentation on this?
thnx!

Cheers,
J.

**Comment by jeanslack** [comment]
> You are right, it's working. I think the issue was a refresh. I use Double Commander and have automatic refresh turned off. So when some file is changed it will not show the change automatically. So when eg. renamed it will not show. I think this was the case. Sorry, my bad.

Don't worry, no problem.

> type error on the page https://jeanslack.github.io/Videomass/Contribute.html . It says TRASLATING iso TRANSLATING

OK, thnx!

> Can you please explain: "setting timestamp" within settings. Can not find any documentation on this?
thnx!

These are the possible settings related to the display of the current play time (using FFplay). Since they do not have auto resizing, they can be changed for proper display playing some videos; These settings are on demand, they are not saved when the program is exited; This is the **drawtext** video filter applied to FFplay library https://ffmpeg.org/ffmpeg-filters.html#drawtext. Maybe the timestamp name on the Videomass menu isn't adequate IMHO.

**Comment by johannesdedoper** [comment]
Within Videomass you have a setting called "setting timestamp" (see picture).
What does this do and how does it work?
![Tooltip_001](https://user-images.githubusercontent.com/100475891/160300190-e8eb3183-83b5-4ff9-8bea-79c72b07d80e.png)
Cheers, J

**Comment by johannesdedoper** [comment]
> These are the possible settings related to the display of the current play time (using FFplay). Since they do not have auto resizing, they can be changed for proper display playing some videos; These settings are on demand, they are not saved when the program is exited; This is the drawtext video filter applied to FFplay library https://ffmpeg.org/ffmpeg-filters.html#drawtext. Maybe the timestamp name on the Videomass menu isn't adequate IMHO.

Ok, so this timestamp will/can not be burned-in? Only invisible when playing a file in Videomass.

**Comment by jeanslack** [comment]
Yes sure, to be burned-in you have to use ffmpeg of course. Try adding this line to some your video encoding profiles:
`-vf "drawtext=fontfile=Arial:text='%{pts\:hms}':fontcolor=White:shadowcolor=Black:shadowx=1:shadowy=1:fontsize=32:box=1:boxcolor=DeepPink:x=(w-tw)/2:y=h(2*lh)"`

Using ffplay it is VISIBLE only when playing a file in Videomass.
Did you want to know this?
